version: '3'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - DATABASE_HOST=127.0.01
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=practica
      - POSTGRES_DB=persona
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: tonny@lema.com
      PGADMIN_DEFAULT_PASSWORD: practica
    ports:
      - 5050:80
    depends_on:
      - postgresql
    networks:
      - mynetwork

  jaeger-allinone:
    image: jaegertracing/all-in-one:1.25
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    depends_on:
      - postgresql
    networks:
      - mynetwork

  app:
    container_name: practica-app
    image: pee-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgresql:5432/persona
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=practica
      - JAEGER_HTTP_SENDER_URLY=http://jaeger-allinone:14268/api/traces
    depends_on:
      - postgresql
      - jaeger-allinone
    networks:
      - mynetwork

networks:
  mynetwork:
